spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    password: dbuser
    username: dbuser
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  servlet:
    context-path: /funtm
  port: 8081
